version: '3'

services:
  jupyter:
    build: .
    command: jupyter lab --allow-root --ip=0.0.0.0 --notebook-dir='/app' --NotebookApp.token=''
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
